### ISSUE TITLE
numba.core.errors.TypingError

### ISSUE THREAD

**Issue by vkkodali** [DessimozLab/omamer#13]
I am getting the following error when running `omamer search`. Could you please help me? 

```bash
$ omamer search --db ../omamer_databases/LUCA.h5 --query ~/GitHub/OMArk/example_data/UP000005640_9606.fasta --out temp.out
Searching: 0it [00:00, ?it/s]0 second to load query sequences
Traceback (most recent call last):
  File "/home/kodalivk/envs/omark_env/bin/omamer", line 190, in <module>
    args.func(args)
  File "/home/kodalivk/envs/omark_env/lib/python3.9/site-packages/omamer/_runners.py", line 110, in search
    ms.merge_search(
  File "/home/kodalivk/envs/omark_env/lib/python3.9/site-packages/omamer/merge_search.py", line 1227, in merge_search
    ref_fam_counts = self.ref_fam_counts_max
  File "/home/kodalivk/envs/omark_env/lib/python3.9/site-packages/property_manager/__init__.py", line 788, in __get__
    value = super(custom_property, self).__get__(obj, type)
  File "/home/kodalivk/envs/omark_env/lib/python3.9/site-packages/omamer/merge_search.py", line 1205, in ref_fam_counts_max
    return self.ref_hog_counts_max[self.db._fam_tab.col('HOGoff')]
  File "/home/kodalivk/envs/omark_env/lib/python3.9/site-packages/property_manager/__init__.py", line 788, in __get__
    value = super(custom_property, self).__get__(obj, type)
  File "/home/kodalivk/envs/omark_env/lib/python3.9/site-packages/omamer/merge_search.py", line 1199, in ref_hog_counts_max
    return cumulate_counts_nfams(
  File "/home/kodalivk/envs/omark_env/lib/python3.9/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/kodalivk/envs/omark_env/lib/python3.9/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function zeros>) found for signature:
 
 >>> zeros(UniTuple(int64 x 1), dtype=class(uint64))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'ol_np_zeros': File: numba/np/arrayobj.py: Line 4164.
    With argument(s): '(UniTuple(int64 x 1), dtype=class(uint64))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<built-in function empty>) found for signature:
    
    >>> empty(UniTuple(int64 x 1), dtype=class(uint64))
    
   There are 2 candidate implementations:
         - Of which 2 did not match due to:
         Overload in function 'ol_np_empty': File: numba/np/arrayobj.py: Line 4086.
           With argument(s): '(UniTuple(int64 x 1), dtype=class(uint64))':
          Rejected as the implementation raised a specific error:
            ValueError: Failed in nopython mode pipeline (step: native lowering)
          Invalid initialization option
     raised from /home/kodalivk/envs/omark_env/lib/python3.9/site-packages/numba/core/targetconfig.py:295
   
   During: resolving callee type: Function(<built-in function empty>)
   During: typing of call at /home/kodalivk/envs/omark_env/lib/python3.9/site-packages/numba/np/arrayobj.py (4169)
   
   
   File "../omark_env/lib/python3.9/site-packages/numba/np/arrayobj.py", line 4169:
       def impl(shape, dtype=float):
           arr = np.empty(shape, dtype=dtype)
           ^

  raised from /home/kodalivk/envs/omark_env/lib/python3.9/site-packages/numba/core/typeinfer.py:1086

During: resolving callee type: Function(<built-in function zeros>)
During: typing of call at /home/kodalivk/envs/omark_env/lib/python3.9/site-packages/omamer/merge_search.py (224)


File "../omark_env/lib/python3.9/site-packages/omamer/merge_search.py", line 224:
def cumulate_counts_1fam(
    <source elided>

    current_best_child_count = np.zeros(hog_cum_counts.shape, dtype=np.uint64)
    ^

During: resolving callee type: type(CPUDispatcher(<function cumulate_counts_1fam at 0x7ff1b8783280>))
During: typing of call at /home/kodalivk/envs/omark_env/lib/python3.9/site-packages/omamer/merge_search.py (260)

During: resolving callee type: type(CPUDispatcher(<function cumulate_counts_1fam at 0x7ff1b8783280>))
During: typing of call at /home/kodalivk/envs/omark_env/lib/python3.9/site-packages/omamer/merge_search.py (260)


File "../omark_env/lib/python3.9/site-packages/omamer/merge_search.py", line 260:
def cumulate_counts_nfams(
    <source elided>

        main_fun(hog_cum_counts, fam_level_offsets, hog2parent, cum_fun, prop_fun)
        ^

Closing remaining open files:../omamer_databases/LUCA.h5...done
Searching: 0it [00:19, ?it/s]   
```

**Comment by alex-wave** [comment]
Hello, 

Thanks for your message. This looks like an error from numba when it is compiling the code, when it is allocating an array to store some intermediate results.

Unfortunately we have been unable to replicate this error. Please could you send us a list of the versions of packages you have installed? You can easily list them using `conda env export` or `pip list` dependent on how you have python installed.

Also, please can you let me know which version of the LUCA OMAmer database you have downloaded? 

Thanks,
Alex

**Comment by vkkodali** [comment]
I am running `omamer` on python version 3.9.16. 
[packages.txt](https://github.com/DessimozLab/omamer/files/10815946/packages.txt) has a list of all the packages I have installed.

**Comment by alex-wave** [comment]
Hello,

I'm unable to reproduce this error, however the database version that you have downloaded is not compatible with the most recent version of the OMAmer package as it doesn't include some data now required. Please can you try downloading the most recent database for the LUCA dataset from the OMA browser website? - https://omabrowser.org/All/LUCA.h5

I think that the last version of OMAmer that supports the database format on that zenodo link is version 0.2.0 (https://pypi.org/project/omamer/0.2.0/). However, I see that you have OMArk installed and I think this relies on the most recent version of OMAmer.


Further, I've tried creating an environment with your packages using `pip install -r req.txt` after rewriting the package list as a requirements file. There was a conflict between `setuptools` versions and `BUSCO` isn't available from PyPI so I had to remove this from the package list. I wouldn't expect `setuptools` to throw this error and it might just be differences between conda / pypi versions. 

```
ERROR: Cannot install -r req.txt (line 29), -r req.txt (line 56) and setuptools==62.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested setuptools==62.1.0
    numba 0.56.4 depends on setuptools
    setuptools-rust 1.5.2 depends on setuptools>=62.4
```

Once I remove the `setuptools` package as well I can install the remaining packages. When running with the LUCA DB from zenodo it gives the expected error, so I am unsure whether the `numba` package is correctly installed on your system.

```
$ omamer search --db LUCA.h5 --query UP000005640_9606.fasta --out temp.out
Searching: 0it [00:00, ?it/s]0 second to load query sequences
299 second to cumulate counts of reference HOGs
47 second to load the k-mer table
149 second for the actual search (~ 66 query/second)
Searching: 10000it [08:17, 20.12it/s]Traceback (most recent call last):
  File "/users/awarwick/.miniconda/envs/omamer-test/bin/omamer", line 190, in <module>
    args.func(args)
  File "/users/awarwick/.miniconda/envs/omamer-test/lib/python3.9/site-packages/omamer/_runners.py", line 114, in search
    df = ms.output_results(overlap=0, fst=0, sst=args.threshold, ref_taxon=args.reference_taxon)
  File "/users/awarwick/.miniconda/envs/omamer-test/lib/python3.9/site-packages/omamer/merge_search.py", line 1389, in output_results
    return pd.DataFrame(zip(*r), columns=c)
  File "/users/awarwick/.miniconda/envs/omamer-test/lib/python3.9/site-packages/pandas/core/frame.py", line 738, in __init__
    data = list(data)
  File "/users/awarwick/.miniconda/envs/omamer-test/lib/python3.9/site-packages/omamer/merge_search.py", line 1360, in <lambda>
    map(lambda x: self.hog_tab['MedianSeqLen'][x] if x != -1 else 'na', q2hog_off)]
ValueError: no field of name MedianSeqLen
Closing remaining open files:LUCA.h5...done
Searching: 10000it [08:18, 20.05it/s]
```

I will update the README to make the database change more obvious.

Thanks,
Alex

**Comment by vkkodali** [comment]
I am still getting the same error with the latest version of the db. Apparently the `packages.txt` file includes all packages that were installed by our admin as well. Here's the list of packages I see with `pip freeze --local` and it does not include setuptools: 
```
biopython==1.81                 Jinja2==3.1.2                   omark==0.2.4                    requests==2.28.2
blosc2==2.0.0                   kiwisolver==1.4.4               packaging==23.0                 scipy==1.10.1
certifi==2022.12.7              llvmlite==0.39.1                pandas==1.5.3                   tables==3.8.0
charset-normalizer==3.0.1       MarkupSafe==2.1.2               Pillow==9.4.0                   tqdm==4.64.1
contourpy==1.0.7                matplotlib==3.7.0               property-manager==3.0           urllib3==1.26.14
cycler==0.11.0                  msgpack==1.0.4                  py-cpuinfo==9.0.0               verboselogs==1.7
Cython==0.29.33                 numba==0.56.4                   pyparsing==3.0.9                wget==3.2
ete3==3.1.2                     numexpr==2.8.4                  PySAIS==1.0.8                   zenodo-get==1.3.4
fonttools==4.38.0               numpy==1.23.5                   python-dateutil==2.8.2
humanfriendly==10.0             omamer==0.2.3                   pytz==2022.7.1
```
As you have noticed, I installed `OMArk` and my main goal is to be able to run `OMArk` locally. Is there a way to install `omamer` and `omark` using `conda`?

**Comment by vkkodali** [comment]
Finally, I got it to work! I still don't know what the issue was though. 
I just created a new conda environment with python 3.9.16 and installed OMark using pip. From what I can tell, the versions of all packages are the same between my conda env and the virtualenv. I am closing the issue, but feel free to investigate further if you want to get to the bottom of this. I'd be happy to answer any further questions you may have about my virtualenv.
