### ISSUE TITLE
mkdb crash with the latest OMA release

### ISSUE THREAD

**Issue by nromashchenko** [DessimozLab/omamer#40]
Version 2.0.4 fails to build a database based on the latest OMA release with the following crash:
```
INFO:  - species_tree: None
INFO:  - sequences: None
INFO:  - log_level: debug
INFO:  - func: <function mkdb_oma at 0x7f54782bf920>
WARNING: Overwriting database file (test.h5)
INFO: Loading sequences
DEBUG: initiate taxonomy table
DEBUG: parsing species tree /work/FAC/FBM/DBC/cdessim2/oma/oma-browser/All.Jul2024/data/speciestree.nwk
DEBUG: select and strip OMA HOGs
Parsing HOGs: 100%|██████████| 33451292/33451292 [06:35<00:00, 84567.45it/s]
DEBUG: fill sequence buffer, species table and initiate protein table
DEBUG:  - select proteins from selected HOGs
Parsing genomes:   0%|          | 0/2927 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/users/nromashc/miniforge3/envs/omamer/bin/omamer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/users/nromashc/miniforge3/envs/omamer/lib/python3.12/site-packages/omamer/main.py", line 304, in main
    args.func(args)
  File "/users/nromashc/miniforge3/envs/omamer/lib/python3.12/site-packages/omamer/_runners.py", line 108, in mkdb_oma
    seq_buff = db.build_database(oma_db_fn, nwk)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/nromashc/miniforge3/envs/omamer/lib/python3.12/site-packages/omamer/database.py", line 1439, in build_database
    ) = self.select_and_filter_OMA_proteins(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/users/nromashc/miniforge3/envs/omamer/lib/python3.12/site-packages/omamer/database.py", line 1553, in select_and_filter_OMA_proteins
    seq = oma_seq_buffer[oma_seq_off : oma_seq_off + seq_len + 1]
          ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
```

I run it as

```
omamer mkdb --db $db_name --nthreads 6 --min_fam_completeness 0.5 --logic OR --oma_path $oma_path --log_level debug
```
for packages
```
tables==3.9.2
numpy==1.26.4
pandas==2.2.2
```
and python 3.12.4. I however had it also for 3.11 and 3.10. Seems to be a numpy issue as `oma_seq_off + seq_len + 1` is casted to np.float64 from np.uint64, np.int64.

**Comment by nromashchenko** [comment]
had been fixed by [ca69](https://github.com/DessimozLab/omamer/commit/ca69493e1120600a2b6697f8eee2bc8b9de9683e) the whole time, but wasn't released
